--合同模板系统变量初始化
SET IDENTITY_INSERT [dbo].[ContTxtTempVarStore] ON 

INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (1, N'当前日期', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (2, N'供应商账号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (3, N'供应商开户银行', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (4, N'客户税务登记号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (5, N'客户开户银行账号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (6, N'客户开票地址电话', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (7, N'客户开票名称', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (8, N'对方传真', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (9, N'对方邮编', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (10, N'对方联系地址', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (11, N'对方联系电话', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (12, N'对方法定代表人', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (13, N'合同对方', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (14, N'签约主体传真', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (15, N'签约主体开票名称', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (16, N'签约主体电话', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (17, N'签约主体邮编', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (18, N'签约主体地址', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (19, N'签约主体账号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (20, N'签约主体开户银行', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (21, N'签约主体税务登记号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (22, N'签约主体法定代表人', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (23, N'签约主体', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (24, N'合同计划完成日期', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (25, N'合同生效日期', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (26, N'合同签订日期', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (27, N'标的明细', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (28, N'合同收货方式', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (29, N'合同收货人联系电话', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (30, N'合同收货人', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (31, N'合同收货邮编', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (32, N'合同收货地址', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (33, N'币种', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (34, N'合同金额大写', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (35, N'合同金额小写', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (36, N'合同编号', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (37, N'合同名称', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ([Id], [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (38, N'标的概要', NULL, 0, 0, NULL, 0, NULL)
SET IDENTITY_INSERT [dbo].[ContTxtTempVarStore] OFF

--修改系统变量
update [ContTxtTempVarStore] set Isdelete=1 where Id in(5,28,29,30,31,32)


INSERT [dbo].[ContTxtTempVarStore] ( [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES ( N'客户开户银行', NULL, 0, 0, NULL, 0, NULL)
INSERT [dbo].[ContTxtTempVarStore] ( [Name], [Code], [IsCustomer], [Isdelete], [TempHistId], [StoreType], [OriginalID]) VALUES (N'客户开户账号', NULL, 0, 0, NULL, 0, NULL)