SET IDENTITY_INSERT [dbo].[Province] ON 

INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (1, 1, N'北京', N'北京', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (2, 1, N'上海', N'上海', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (3, 1, N'天津', N'天津', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (4, 1, N'重庆', N'重庆', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (5, 1, N'安徽', N'安徽', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (6, 1, N'福建', N'福建', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (7, 1, N'甘肃', N'甘肃', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (8, 1, N'广东', N'广东', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (9, 1, N'广西', N'广西', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (10, 1, N'贵州', N'贵州', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (11, 1, N'海南', N'海南', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (12, 1, N'河北', N'河北', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (13, 1, N'河南', N'河南', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (14, 1, N'黑龙江', N'黑龙江', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (15, 1, N'湖北', N'湖北', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (16, 1, N'湖南', N'湖南', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (17, 1, N'吉林', N'吉林', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (18, 1, N'江苏', N'江苏', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (19, 1, N'江西', N'江西', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (20, 1, N'辽宁', N'辽宁', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (21, 1, N'内蒙古', N'内蒙古', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (22, 1, N'宁夏', N'宁夏', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (23, 1, N'青海', N'青海', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (24, 1, N'山东', N'山东', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (25, 1, N'山西', N'山西', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (26, 1, N'陕西', N'陕西', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (27, 1, N'四川', N'四川', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (28, 1, N'西藏', N'西藏', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (29, 1, N'新疆', N'新疆', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (30, 1, N'云南', N'云南', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (31, 1, N'浙江', N'浙江', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (32, 1, N'香港', N'香港', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (33, 1, N'澳门', N'澳门', 1)
INSERT [dbo].[Province] ([Id], [CountryId], [Name],[DisplayName], [IsEnable]) VALUES (34, 1, N'台湾', N'台湾', 1)
SET IDENTITY_INSERT [dbo].[Province] OFF